#- hosts: all
#  become: true

#  tasks:
    #- debug:
    #    var: ansible_facts
    #- name: install packages
    #  become: yes
    #  become_user: root
    #  #become_method: sudo
    #  action: >
    #    {{ ansible_pkg_mgr }} name=htop state=present update_cache=yes
    - debug:
        msg: "{{ansible_fqdn}}"

    - name: ping
      become: true
      ansible.builtin.ping:


    - name: add repo zabbix gpg key
      ansible.builtin.rpm_key:
        state: present
        key: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591-EL5
      when: ansible_facts['os_family'] == "RedHat"

    - name: add repo zabbix-agent2 rhel family 9
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-release-6.0-4.el9.noarch.rpm
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9"
    
    - name: add repo zabbix-agent2 rhel family 8
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"

    - name: add repo zabbix-agent2 rhel family 7
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-4.el7.noarch.rpm
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"

    - name: add repo zabbix-agent2 rhel family 6
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/6/x86_64/zabbix-release-6.0-4.el6.noarch.rpm
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "6"


    - name: install zabbix agent2
      ansible.builtin.yum:
        name:
          - zabbix-agent2
          - zabbix-agent2-plugin-*
        state: present
      when: ansible_facts['os_family'] == "RedHat"



    - name: install zabbix-agent2 debian 11
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix/zabbix-agent2_6.0.5-1%2Bdebian11_amd64.deb
        state: present
        #update_cache: yes
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution_major_version'] == "11"

    - name: install zabbix-agent2 debian 10
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix/zabbix-agent_6.0.5-1%2Bdebian10_amd64.deb
        state: present
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution_major_version'] == "10"
    
    - name: install zabbix-agent2 debian 9
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix/zabbix-agent_6.0.5-1%2Bdebian9_amd64.deb
        state: present
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution_major_version'] == "9"



    - name: pkg install pkgutil
      #ansible.builtin.shell: pkgadd -d http://get.opencsw.org/now
      svr4pkg:
        name: CSWpkgutil
        src: 'http://get.opencsw.org/now'
        state: present
        #category: true
        zone: current
      when: ansible_facts['os_family'] == "Solaris"

    - name: pkg install libpcre-dev
      become: true
      pkgutil:
        name: CSWlibpcre-dev
        state: present
      when: ansible_facts['os_family'] == "Solaris"

    - name: group add zabbix
      ansible.builtin.group:
        name: zabbix
        state: present
      when: ansible_facts['os_family'] == "Solaris"

    - name: useradd zabbix to zabbix group
      ansible.builtin.user:
        name: zabbix
        group: zabbix
      when: ansible_facts['os_family'] == "Solaris"

    - name: Creates directory
      file:
        path: /usr/local
        state: directory
      when: ansible_facts['os_family'] == "Solaris"

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./zabbix-agent-solaris/
        dest: /usr/local
        owner: zabbix
        group: zabbix 
        mode: '0644'
      when: ansible_facts['os_family'] == "Solaris"

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /tmp/zabbix_agentd.log
        owner: zabbix
        group: zabbix
        state: touch
        mode: '0644'
      when: ansible_facts['os_family'] == "Solaris"

    - name: Changing permission
      file: dest=/usr/local/sbin/zabbix_agentd mode=a+x
      when: ansible_facts['os_family'] == "Solaris"


    - name: install service
      ansible.builtin.shell: svcbundle -o zabbix-agentd.xml -s service-name=application/zabbix-agentd -s model=daemon -s start-method="/usr/local/sbin/zabbix_agentd -c /usr/local/etc/zabbix_agentd.conf"
      when: ansible_facts['os_family'] == "Solaris"

    - name: install svc
      ansible.builtin.shell: svccfg import /usr/local/share/zabbix-agentd.xml
      when: ansible_facts['os_family'] == "Solaris"
    
    - name: replace line server
      lineinfile:
        path: /usr/local/etc/zabbix_agentd.conf
        #regexp: '^127\.0\.0\.1'
        search_string: 'Server=127.0.0.1'
        line: Server=auatiapp01.amkor.com
        #backrefs: yes
      when: ansible_facts['os_family'] == "Solaris"

    - name: replace line server-active
      lineinfile:
        path: /usr/local/etc/zabbix_agentd.conf
        search_string: 'ServerActive=127.0.0.1'
        #regexp: '^127\.0\.0\.1'
        line: ServerActive=auatiapp01.amkor.com
        #backrefs: yes
      when: ansible_facts['os_family'] == "Solaris"

    - name: replace line hostname
      lineinfile:
        path: /usr/local/etc/zabbix_agentd.conf
        search_string: 'Hostname=Zabbix server'
        #regexp: 'Zabbix server'
        line: Hostname={{ansible_fqdn}}
        #backrefs: yes
      when: ansible_facts['os_family'] == "Solaris"

    - name: Enable service zabbix-agentd
      ansible.builtin.service:
        name: zabbix-agentd
        enabled: yes
      when: ansible_facts['os_family'] == "Solaris"
      



    #- name: copy zabbix_agent2.conf
    #  copy:
    #    src: zabbix_agent2.conf
    #    dest: /etc/zabbix/
    #    force: yes
    #  when: ansible_facts['system'] == "Linux"


    - name: replace line server
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf 
        search_string: 'Server='
        line: Server={{zabbix_server}}
      when: ansible_facts['system'] == "Linux"
        #backrefs: yes
    
    - name: replace line server-active
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf 
        search_string: 'ServerActive='
        line: ServerActive={{zabbix_server}}
        #backrefs: yes
      when: ansible_facts['system'] == "Linux"

    - name: replace line hostname
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf 
        search_string: 'Hostname='
        line: Hostname={{ansible_fqdn}}
        #backrefs: yes
      when: ansible_facts['system'] == "Linux"
        
    - name: enable service zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        enabled: yes
      when: ansible_facts['system'] == "Linux"

    - name: start service zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted
      when: ansible_facts['system'] == "Linux"
