- hosts: all
  become: true
  vars:
    user:
      - name: "kube"
        password: "secret"
        ssh_key: "ssh-rsa …"

  tasks:
    - name: install packages
      become: true
      become_user: root
      action: >
        {{ ansible_pkg_mgr }} name=htop state=present update_cache=yes
