- hosts: all
  become: true

  tasks:
    #- debug:
    #    var: ansible_facts
    #- name: install packages
    #  become: yes
    #  become_user: root
    #  #become_method: sudo
    #  action: >
    #    {{ ansible_pkg_mgr }} name=htop state=present update_cache=yes
    - debug:
        msg: "{{ansible_fqdn}}"

    - name: ping
      become: true
      ansible.builtin.ping:


    - name: import zabbix gpg key
      ansible.builtin.rpm_key:
        state: present
        key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591-EL5
      when: ansible_facts['os_family'] == "RedHat"
    
    - name: install zabbix-agent2 rhel family 8
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-agent2-6.0.0-1.el8.x86_64.rpm
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"

    - name: install zabbix-agent2 rhel family 7
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-agent2-6.0.5-1.el7.x86_64.rpm
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"

    - name: install zabbix-agent2 rhel family 6
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/6/x86_64/zabbix-agent2-6.0.5-1.el6.x86_64.rpm
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "6"



    - name: install zabbix-agent2 debian 11
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix/zabbix-agent2_6.0.5-1%2Bdebian11_amd64.deb
        state: present
        #update_cache: yes
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution_major_version'] == "11"

    - name: install zabbix-agent2 debian 10
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix/zabbix-agent_6.0.5-1%2Bdebian10_amd64.deb
        state: present
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution_major_version'] == "10"
    
    - name: install zabbix-agent2 debian 9
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix/zabbix-agent_6.0.5-1%2Bdebian9_amd64.deb
        state: present
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution_major_version'] == "9"


    - name: copy zabbix_agent2.conf
      copy:
        src: zabbix_agent2.conf
        dest: /etc/zabbix/
        force: yes

    - name: replace line server
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf 
        search_string: 'Server=127.0.0.1'
        line: Server=muzabapd01.my.ds.amkor.com
        #backrefs: yes
    
    - name: replace line server-active
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf 
        search_string: 'ServerActive=127.0.0.1'
        line: ServerActive=muzabapd01.my.ds.amkor.com
        #backrefs: yes

    - name: replace line hostname
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf 
        search_string: 'Hostname=Zabbix server'
        line: Hostname={{ansible_fqdn}}
        #backrefs: yes
        
    - name: enable service zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        enabled: yes

    - name: start service zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted
